# Generated by Django 6.1.1 on 2026-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_code', models.CharField(blank=True, help_text='eSewa transaction_code returned on success', max_length=100, null=True)),
                ('ref_id', models.CharField(blank=True, help_text='eSewa refId if any', max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product_delivery_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_code', models.CharField(default='EPAYTEST', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('FULL_REFUND', 'Full Refund'), ('PARTIAL_REFUND', 'Partial Refund')], default='PENDING', max_length=20)),
                ('signature', models.TextField(blank=True)),
                ('esewa_response_data', models.JSONField(blank=True, null=True)),
                ('esewa_response_b64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eSewa Payment',
                'verbose_name_plural': 'eSewa Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
