# Generated by Django 6.1.1 on 2026-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esewa_app', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EsewaPayment',
        ),
    ]
